name: python_grundlagen
channels:
  - conda-forge
dependencies:
  - python=3.13
  - jupyter
  - ipykernel
  - ipython
  - notebook
  - numpy
  - scipy
  - matplotlib
  - pandas=3.0
  - requests
  - tifffile
